# jenkins sshs into the ec2 and runs this to start both containers
version: '3.8' 
services:
  java-maven-app:
  #using the image built with the Dockerfile
    image: ${IMAGE} 
    ports:
      - 8080:8080
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=my-pwdx